export type Promo = {
  id: number;
  image: string;
  phoneImage: string;
  name: string;
  type: string;
  data: string;
};

const imagePath = "./src/assets/images";

export const promoData: Promo[] = [
  {
    id: 1,
    image: `${imagePath}/carousel_images/desktop_images/promo1.jpg`,
    phoneImage: `${imagePath}/carousel_images/phone_images/promo_phone1.jpg`,
    name: `${imagePath}/icons_png/carousel_icons/movie_name1.png`,
    type: "Thriller",
    data: "The rescue is only the beginning.",
  },
  {
    id: 2,
    image: `${imagePath}/carousel_images/desktop_images/promo2.jpg`,
    phoneImage: `${imagePath}/carousel_images/phone_images/promo_phone2.jpg`,
    name: `${imagePath}/icons_png/carousel_icons/movie_name2.png`,
    type: "Comedy",
    data: "Start your holidays on a high note.",
  },
  {
    id: 3,
    image: `${imagePath}/carousel_images/desktop_images/promo3.jpg`,
    phoneImage: `${imagePath}/carousel_images/phone_images/promo_phone3.jpg`,
    name: `${imagePath}/icons_png/carousel_icons/movie_name3.png`,
    type: "Comedy",
    data: "One new office. Same augmented reality.",
  },
  {
    id: 4,
    image: `${imagePath}/carousel_images/desktop_images/promo4.jpg`,
    phoneImage: `${imagePath}/carousel_images/phone_images/promo_phone4.jpg`,
    name: `${imagePath}/icons_png/carousel_icons/movie_name4.png`,
    type: "Documentary",
    data: "Every breath, a breakthrough.",
  },
  {
    id: 5,
    image: `${imagePath}/carousel_images/desktop_images/promo5.jpg`,
    phoneImage: `${imagePath}/carousel_images/phone_images/promo_phone5.jpg`,
    name: `${imagePath}/icons_png/carousel_icons/movie_name5.png`,
    type: "Thriller",
    data: "New Season.",
  },
  {
    id: 6,
    image: `${imagePath}/carousel_images/desktop_images/promo6.jpg`,
    phoneImage: `${imagePath}/carousel_images/phone_images/promo_phone6.jpg`,
    name: `${imagePath}/icons_png/carousel_icons/movie_name6.png`,
    type: "Drama",
    data: "New film.",
  },
  {
    id: 7,
    image: `${imagePath}/carousel_images/desktop_images/promo7.jpg`,
    phoneImage: `${imagePath}/carousel_images/phone_images/promo_phone7.jpg`,
    name: `${imagePath}/icons_png/carousel_icons/movie_name7.png`,
    type: "Documentary",
    data: "His story in his words.",
  },
  {
    id: 8,
    image: `${imagePath}/carousel_images/desktop_images/promo8.jpg`,
    phoneImage: `${imagePath}/carousel_images/phone_images/promo_phone8.jpg`,
    name: `${imagePath}/icons_png/carousel_icons/movie_name8.png`,
    type: "Comedy",
    data: "Dream mas grande!",
  },
  {
    id: 9,
    image: `${imagePath}/carousel_images/desktop_images/promo9.jpg`,
    phoneImage: `${imagePath}/carousel_images/phone_images/promo_phone9.jpg`,
    name: `${imagePath}/icons_png/carousel_icons/movie_name9.png`,
    type: "Drama",
    data: "Two brothers. One final request.",
  },
  {
    id: 10,
    image: `${imagePath}/carousel_images/desktop_images/promo10.jpg`,
    phoneImage: `${imagePath}/carousel_images/phone_images/promo_phone10.jpg`,
    name: `${imagePath}/icons_png/carousel_icons/movie_name10.png`,
    type: "Drama",
    data: "Based on the international best-selling novel.",
  },
  {
    id: 11,
    image: `${imagePath}/carousel_images/desktop_images/promo11.jpg`,
    phoneImage: `${imagePath}/carousel_images/phone_images/promo_phone11.jpg`,
    name: `${imagePath}/icons_png/carousel_icons/movie_name11.png`,
    type: "Drama",
    data: "Friendship has no last call.",
  },
  {
    id: 12,
    image: `${imagePath}/carousel_images/desktop_images/promo12.jpg`,
    phoneImage: `${imagePath}/carousel_images/phone_images/promo_phone12.jpg`,
    name: `${imagePath}/icons_png/carousel_icons/movie_name12.png`,
    type: "Drama",
    data: "The epic series comes to an end.",
  },
  {
    id: 13,
    image: `${imagePath}/carousel_images/desktop_images/promo13.jpg`,
    phoneImage: `${imagePath}/carousel_images/phone_images/promo_phone13.jpg`,
    name: `${imagePath}/icons_png/carousel_icons/movie_name13.png`,
    type: "Drama",
    data: "Family. It's a killer.",
  },
  {
    id: 14,
    image: `${imagePath}/carousel_images/desktop_images/promo14.jpg`,
    phoneImage: `${imagePath}/carousel_images/phone_images/promo_phone14.jpg`,
    name: `${imagePath}/icons_png/carousel_icons/movie_name14.png`,
    type: "Animation",
    data: "Sometimes all you need is for everything to go wrong.",
  },
  {
    id: 15,
    image: `${imagePath}/carousel_images/desktop_images/promo15.jpg`,
    phoneImage: `${imagePath}/carousel_images/phone_images/promo_phone15.jpg`,
    name: `${imagePath}/icons_png/carousel_icons/movie_name15.png`,
    type: "Mystery",
    data: "Who do you trust when you can't trust yourself?",
  },
  {
    id: 16,
    image: `${imagePath}/carousel_images/desktop_images/promo16.jpg`,
    phoneImage: `${imagePath}/carousel_images/phone_images/promo_phone16.jpg`,
    name: `${imagePath}/icons_png/carousel_icons/movie_name16.png`,
    type: "Comedy",
    data: "Four Emmy wins including Outstanding Comedy.",
  },
  {
    id: 17,
    image: `${imagePath}/carousel_images/desktop_images/promo17.jpg`,
    phoneImage: `${imagePath}/carousel_images/phone_images/promo_phone17.jpg`,
    name: `${imagePath}/icons_png/carousel_icons/movie_name17.png`,
    type: "Comedy",
    data: "She's about to change her fortune.",
  },
  {
    id: 18,
    image: `${imagePath}/carousel_images/desktop_images/promo18.jpg`,
    phoneImage: `${imagePath}/carousel_images/phone_images/promo_phone18.jpg`,
    name: `${imagePath}/icons_png/carousel_icons/movie_name18.png`,
    type: "Documentary",
    data: "Unknown. Unexplained. Unbelievable. Until now.",
  },
  {
    id: 19,
    image: `${imagePath}/carousel_images/desktop_images/promo19.jpg`,
    phoneImage: `${imagePath}/carousel_images/phone_images/promo_phone19.jpg`,
    name: `${imagePath}/icons_png/carousel_icons/movie_name19.png`,
    type: "Drama",
    data: "The race continues.",
  },
];
